version: '3'
services:
  # 服务名称
  dev:
    # 镜像:版本
    image: ghcr.io/growdu/oh-my-code/coder:v1.5
    restart: always
    container_name: coder
    # 本地 8085 -> 容器 8080
    ports:
      - '8085:8080'
      - '10028:22'
      - '3000:3000'
      - '10000:10000'
      - '10024:10024'
      - '10087:10087'
      - '10088:10088'
      - '10089:10089'
      - '10090:10090'
      # 3000 ,10000,10024用于开发调试
    environment:
      - PASSWORD=coder
    # 数据卷 映射本地文件到容器
    volumes:
      - ./entrypoint.sh:/usr/bin/entrypoint.sh
      - ./hosts:/etc/hosts
      - /home/ha/work:/home/coder/work
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - CAP_SYS_ADMIN
      - SYS_PTRACE
    working_dir: /home/coder/
    command: /usr/sbin/init
    hostname: coder

